version: '3.7'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - voices
  web:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - voices
    volumes:
      - .:/app

volumes:
  postgres_data:
networks:
  voices:
