version: '3.7'
services:
  db:
    image: bitnami/postgresql:15.1.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgresql
    env_file:
      - .env
    environment:
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_REPLICATION_MODE=master
    networks:
      - voices-dev
  web:
    image: startupcifra/voices-backend:${IMAGE_TAG}
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    restart: always
    depends_on:
      - db
    networks:
      - voices-dev
    command:
      - python
      - main.py
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - voices-dev
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_dbms_memory_pagecache_size=64M
    volumes:
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/import:/var/lib/neo4j/import
      - ${HOME}/neo4j/plugins:/plugins
volumes:
  postgres_data:
networks:
  voices-dev:
    external: true
