version: '3.7'
services:
  db:
    image: bitnami/postgresql:15.1.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgresql
    env_file:
      - .env
    environment:
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_REPLICATION_MODE=master
    networks:
      - voices-dev
  web:
    image: startupcifra/voices-backend:${IMAGE_TAG}
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - ROCKETCHAT_URL=http://rocketchat:3000
        - MONGO_URL=mongodb://mongodb:27017
        - MONGO_REPLICA_SET=rs0
    restart: always
    volumes:
      - static:/app/data
    depends_on:
      - db
    networks:
      - voices-dev
    command:
      - python
      - main.py
  redis:
    image: 'bitnami/redis:6.2.13'
    expose:
      - 6379
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - voices-dev
  worker:
    image: startupcifra/vizme-backend:${IMAGE_TAG}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
    depends_on:
      - db
    networks:
      - voices-dev
    volumes:
      - static:/app/data
    command:
      - celery
      - "-A"
      - vizme.broker
      - worker
      - "-l"
      - INFO
  mongodb:
    image: bitnami/mongodb:5.0
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - MONGODB_ENABLE_JOURNAL=true
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=7017
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017"
    networks:
      - rocketchat
      - voices-dev
    restart: always
  rocketchat:
    image: rocketchat/rocket.chat:6.1.7
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      PORT: 3000
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - rocketchat
      - voices-dev
volumes:
  postgres_data:
  mongodb_data:
  static:
networks:
  voices-dev:
    external: true
  rocketchat:
    external: true
