version: '3.7'
services:
  db:
    image: postgres
    ports:
      - 6432:6432
    env_file:
      - .env
    networks:
      - voices
  web:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - voices
networks:
  voices:
