version: '3.7'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE}
    networks:
      - voices
  web:
    image: startupcifra/voices-backend:${IMAGE_TAG}
    command:
      - python
      - main.py
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    restart: always
    depends_on:
      - db
    networks:
      - voices
    volumes:
      - .:/app
  chat:
    image: startupcifra/voices-backend:${IMAGE_TAG}
    command:
      - python
      - server.py
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    restart: always
    depends_on:
      - db
    networks:
      - voices
    volumes:
      - .:/chat-app
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - voices
    environment:
      - NEO4J_AUTH=neo4j/eco_system
      - NEO4J_dbms_memory_pagecache_size=64M
    volumes:
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/import:/var/lib/neo4j/import
      - ${HOME}/neo4j/plugins:/plugins

volumes:
  postgres_data:
networks:
  voices:
