"""tags

Revision ID: 95743a5cd720
Revises: c8d5607cbe94
Create Date: 2023-08-24 19:28:41.816466

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "95743a5cd720"
down_revision = "c8d5607cbe94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("initiatives", sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("initiatives", sa.Column("ar_model", sa.String(length=2000), nullable=True))
    op.create_unique_constraint(None, "users_friends", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_friends", type_="unique")
    op.drop_column("initiatives", "ar_model")
    op.drop_column("initiatives", "tags")
    # ### end Alembic commands ###
