"""support

Revision ID: 4d9969206a08
Revises: 5df56aa8e08c
Create Date: 2023-11-15 21:41:05.272070

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d9969206a08"
down_revision = "5df56aa8e08c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initiatives_supports",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("initiative_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["initiative_id"],
            ["initiatives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id", "initiative_id", name="_user_initiative_supports_idx"),
    )
    op.add_column("initiatives", sa.Column("supports_count", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("initiatives", "supports_count")
    op.drop_table("initiatives_supports")
    # ### end Alembic commands ###
