"""update Notification

Revision ID: 04e707931d75
Revises: 3454c58cc663
Create Date: 2023-08-24 02:10:57.287825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e707931d75'
down_revision = '3454c58cc663'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firebase_token',
    sa.Column('owner', sa.UUID(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=254), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=350), nullable=True),
    sa.Column('status', sa.String(length=8), server_default='UNREADED', nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('firebase_token')
    # ### end Alembic commands ###
