"""main text

Revision ID: 3161b987602a
Revises: aebd719bf2f3
Create Date: 2023-05-22 13:52:01.480172

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3161b987602a"
down_revision = "aebd719bf2f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("initiatives", sa.Column("title", sa.String(length=100), nullable=False))
    op.add_column("initiatives", sa.Column("main_text", sa.String(), nullable=False))
    op.create_unique_constraint(None, "initiatives", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "initiatives", type_="unique")
    op.drop_column("initiatives", "main_text")
    op.drop_column("initiatives", "title")
    # ### end Alembic commands ###
