"""upgrade notifications

Revision ID: b1d6fa220d46
Revises: 04e707931d75
Create Date: 2023-09-14 15:33:15.167138

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b1d6fa220d46"
down_revision = "04e707931d75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column(
            "initiative_id", sa.UUID(as_uuid=True), sa.ForeignKey("initiatives.id", ondelete="CASCADE"), nullable=True
        ),
    )
    op.add_column("notifications", sa.Column("initiative_image", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("initiative_id")
    op.drop_column("initiative_image")
    # ### end Alembic commands ###
