"""test

Revision ID: be717b2d5e28
Revises: f6730c589af8
Create Date: 2023-08-08 08:48:08.879582

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be717b2d5e28"
down_revision = "f6730c589af8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("initiatives", sa.Column("from_date", sa.DateTime(), nullable=True))
    op.add_column("initiatives", sa.Column("to_date", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("district", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("birthdate", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "birthdate")
    op.drop_column("users", "district")
    op.drop_column("initiatives", "to_date")
    op.drop_column("initiatives", "from_date")
    # ### end Alembic commands ###
