"""a

Revision ID: 197f0a3d538a
Revises: 74bd3f9cac5e
Create Date: 2023-06-29 20:09:36.134621

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "197f0a3d538a"
down_revision = "74bd3f9cac5e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initiatives_likes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("initiative_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["initiative_id"],
            ["initiatives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id", "initiative_id", name="_user_initiative_idx"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("initiatives_likes")
    # ### end Alembic commands ###
