"""friends_count

Revision ID: 3a9ca236cbae
Revises: 4d9969206a08
Create Date: 2023-11-29 19:55:08.748024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a9ca236cbae"
down_revision = "4d9969206a08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_initiative_supports_idx", "initiatives_supports", type_="unique")
    op.create_unique_constraint(None, "initiatives_supports", ["id"])
    op.add_column("users", sa.Column("friends_count", sa.Integer(), server_default="0", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "friends_count")
    op.drop_constraint(None, "initiatives_supports", type_="unique")
    op.create_unique_constraint("_user_initiative_supports_idx", "initiatives_supports", ["user_id", "initiative_id"])
    # ### end Alembic commands ###
