"""a

Revision ID: f6730c589af8
Revises: 197f0a3d538a
Create Date: 2023-07-03 21:35:45.588649

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f6730c589af8"
down_revision = "197f0a3d538a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "initiatives_likes", ["id"])
    op.alter_column("users", "role", server_default="citizen")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "initiatives_likes", type_="unique")
    # ### end Alembic commands ###
