"""created_at

Revision ID: d25475720458
Revises: c51f8b7a3d6b
Create Date: 2023-05-08 01:29:34.743063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d25475720458"
down_revision = "c51f8b7a3d6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
