"""a

Revision ID: 74bd3f9cac5e
Revises: 9295fa86cf5d
Create Date: 2023-06-28 19:53:25.835845

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74bd3f9cac5e"
down_revision = "9295fa86cf5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("initiatives", sa.Column("status", sa.String(length=6), server_default="active", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("initiatives", "status")
    # ### end Alembic commands ###
