"""users image url

Revision ID: f6cad55e4818
Revises: 3161b987602a
Create Date: 2023-05-22 14:13:06.538723

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f6cad55e4818"
down_revision = "3161b987602a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("image_url", sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image_url")
    # ### end Alembic commands ###
