"""likes_count

Revision ID: 09a21554deff
Revises: f6cad55e4818
Create Date: 2023-05-22 23:15:22.102325

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "09a21554deff"
down_revision = "f6cad55e4818"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("initiatives", sa.Column("likes_count", sa.Integer(), server_default="0", nullable=False))
    op.add_column("initiatives", sa.Column("comments_count", sa.Integer(), server_default="0", nullable=False))
    op.add_column("initiatives", sa.Column("reposts_count", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("initiatives", "comments_count")
    op.drop_column("initiatives", "likes_count")
    op.drop_column("initiatives", "reposts_count")
    # ### end Alembic commands ###
