"""user city

Revision ID: 9295fa86cf5d
Revises: 900da1a8ef74
Create Date: 2023-06-27 23:09:35.639582

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9295fa86cf5d"
down_revision = "900da1a8ef74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "comments", ["id"])
    op.add_column("users", sa.Column("city", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "city")
    op.drop_constraint(None, "comments", type_="unique")
    # ### end Alembic commands ###
