"""yep

Revision ID: 5df56aa8e08c
Revises: b1d6fa220d46
Create Date: 2023-10-01 11:01:26.542242

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5df56aa8e08c"
down_revision = "b1d6fa220d46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "firebase_token", ["id"])
    op.add_column("initiatives", sa.Column("approved", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "notifications", ["id"])
    op.add_column("users", sa.Column("email_approved", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone")
    op.drop_column("users", "email_approved")
    op.drop_constraint(None, "notifications", type_="unique")
    op.drop_column("initiatives", "approved")
    op.drop_constraint(None, "firebase_token", type_="unique")
    # ### end Alembic commands ###
