"""direction

Revision ID: 40afa709f873
Revises: 95743a5cd720
Create Date: 2023-08-24 19:37:26.953080

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40afa709f873"
down_revision = "95743a5cd720"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("initiatives", sa.Column("event_direction", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("initiatives", "event_direction")
    # ### end Alembic commands ###
