"""to date

Revision ID: 3454c58cc663
Revises: be717b2d5e28
Create Date: 2023-08-09 19:46:35.164596

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3454c58cc663"
down_revision = "be717b2d5e28"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initiatives", "from_date", existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=True
    )
    op.alter_column(
        "initiatives", "to_date", existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initiatives", "to_date", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=True
    )
    op.alter_column(
        "initiatives", "from_date", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=True
    )
    # ### end Alembic commands ###
