"""empty message

Revision ID: db8451810874
Revises: 7f8b7637c1d7
Create Date: 2023-04-21 19:08:58.242525

"""
import uuid

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db8451810874"
down_revision = "7f8b7637c1d7"
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.create_table(
        "cats",
        sa.Column("id", sa.UUID, unique=True, primary_key=True, default=lambda: str(uuid.uuid4())),
        sa.Column("name", sa.VARCHAR(15), nullable=False),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
